org: naner
app: functions-timeout
service: functions-timeout

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  longTimeout:
    handler: handlers/long_timeout.long
    timeout: 4

  shortTimeout:
    handler: handlers/short_timeout.short
    timeout: 1
